const KEYS = {
    //购物车中实例的配置信息
    EDIT_INSTANCE_CONFIG: 'EDIT_INSTANCE_CONFIG',
    ORDER_INSTANCE_INFO: 'ORDER_INSTANCE_INFO',
    CART_INSTANCE_INFO: 'CART_INSTANCE_INFO',
    USER_INFO: 'USER_INFO'
};

export default KEYS
